function Datos = Importar_DRS1(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATOSDELESTUDIO = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DATOSDELESTUDIO = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DATOSDELESTUDIO = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Datosdelestudio = importfile("C:\Users\Franco\Desktop\ARTÍCULOS CIENTÍFICOS\ARTÍCULO GENERACIÓN PERCÁPITA\Datos\Datos del estudio.xlsx", "Sheet1", [2, 55]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Aug-2021 15:22:43

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 51];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":P" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Edaddeljefedehogar", "Aguaenlavivienda", "Electricidadenlavivienda", "Celularenlavivienda", "TVenlavivienda", "IngresomensualdelafamiliaS", "Nmerodepersonasenlavivienda", "Gnerodeljefedehogar", "Ocupacindelfejedehogar", "Aosdeeducacindeljefedehogar", "Niveldeeducacindeljefedehogar", "GastomensualenserviciosS", "Recibicapacitacin", "GeneracinpercpitaKghabda", "Servicios", "DiferenciadegastosenserviciosS"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical", "double", "categorical", "double", "categorical", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, "Servicios", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Aguaenlavivienda", "Electricidadenlavivienda", "Celularenlavivienda", "TVenlavivienda", "Gnerodeljefedehogar", "Ocupacindelfejedehogar", "Niveldeeducacindeljefedehogar", "Recibicapacitacin", "Servicios"], "EmptyFieldRule", "auto");

% Import the data
Datos = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":P" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Datos = [Datos; tb]; %#ok<AGROW>
end

NVA = cell2table(Datos.Properties.VariableNames);
NVA = string(NVA{:,:});
NVN = ["Edad del jefe de hogar","Agua en la vivienda",...
    "Electricidad en la vivienda","Celular en la vivienda","TV en la vivienda",...
    "Ingreso mensual de la familia (S/.)","Número de personas en la vivienda",...
    "Género del jefe de hogar","Ocupación del feje de hogar","Años de educación del jefe de hogar",...
    "Nivel de educación del jefe de hogar","Gasto mensual en servicios (S/.)",...
    "Recibió capacitación",...
    "Generación percápita (Kg/hab/día)","Servicios",...
    "Diferencia de gastos en servicios (S/.)"];
Datos = renamevars(Datos,NVA,NVN);
Datos.Servicios = categorical(Datos.Servicios);
end
